name: eps
version: 0.1.0.0
github: "rl-king/eps"
license: BSD3
author: "Ruben Lie King"
maintainer: "hello@rubenlieking.com"
copyright: "2018 Ruben Lie King"


extra-source-files:
  - README.md


description: Please see the README on GitHub at <https://github.com/rl-king/eps#readme>


dependencies:
  - base >= 4.7 && < 5
  - directory
  - aeson
  - bytestring
  - containers
  - http-client
  - http-client-tls
  - servant
  - servant-server
  - text
  - stm
  - wai
  - wai-extra
  - warp

library:
  source-dirs: src/haskell/lib

executables:
  eps:
    main: Main.hs
    source-dirs: src/haskell/app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - eps


tests:
  eps-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - eps
      - QuickCheck
      - hspec
